# 开发环境配置 - 用于vibe coding和开发
# 使用方式: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  app:
    build:
      target: development

    # 开发模式命令 - 启动交互式shell
    command: /bin/bash

    # 保持容器运行
    stdin_open: true
    tty: true

    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG

    # 开发时挂载所有代码，支持热重载
    volumes:
      - ./:/app
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.cache

    # 端口映射（用于调试和服务）
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy端口

    # 资源限制（开发环境可以更宽松）
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  # Jupyter服务自动启动
  jupyter:
    profiles: []  # 移除profile限制，默认启动

    volumes:
      - ./:/app
      - ./notebooks:/app/notebooks
      - jupyter-dev-data:/root/.jupyter

    environment:
      - ENVIRONMENT=development
      - DEBUG=true

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  # VS Code Server（可选）
  vscode:
    image: codercom/code-server:latest
    container_name: script-eval-vscode
    restart: unless-stopped

    command: >
      --auth none
      --disable-telemetry
      /app

    environment:
      - PASSWORD=
      - SUDO_PASSWORD=

    volumes:
      - ./:/app
      - vscode-data:/home/coder/.local/share/code-server

    ports:
      - "8080:8080"

    networks:
      - script-eval-network

    profiles:
      - vscode

volumes:
  jupyter-dev-data:
  vscode-data:
