# 默认评估配置

evaluation:
  # 评估阈值
  pass_threshold: 0.70          # 合格阈值
  excellent_threshold: 0.85     # 优秀阈值

  # LLM评估开关
  use_deepseek_judge: true      # 是否使用DeepSeek进行语义评估
  run_consistency_check: false  # 是否运行自一致性检查
  consistency_runs: 5           # 一致性检查运行次数

  # 评估维度权重
  weights:
    structure: 0.25    # 结构验证权重
    boundary: 0.25     # 场景边界权重
    character: 0.25    # 角色提取权重
    semantic: 0.25     # 语义准确权重

api:
  # DeepSeek API配置
  model: "deepseek-chat"        # 默认模型
  temperature: 0.1              # 评估用温度（低温度保证确定性）
  max_tokens: 4096              # 最大token数
  max_retries: 3                # 最大重试次数
  retry_delay: 2                # 重试延迟（秒）

output:
  # 输出配置
  save_reports: true            # 是否保存详细报告
  report_format:                # 报告格式
    - json
    - html
  output_dir: "outputs"         # 输出目录

logging:
  # 日志配置
  level: "INFO"                 # 日志级别：DEBUG, INFO, WARNING, ERROR
  log_file: "outputs/logs/evaluation.log"
  max_bytes: 10485760          # 10MB
  backup_count: 5

performance:
  # 性能配置
  batch_size: 10               # 批处理大小
  enable_cache: true           # 启用缓存
  cache_dir: ".cache"          # 缓存目录
